### ISSUE TITLE
Using with SIM800L

### ISSUE THREAD

**Issue by masalinas** [vwochnik/sim900client#4]
Is possible use your librarie with a SIM800 modem?. 

I have a seeeduino GPRS with a SIM800L GPRS modem

Regards

**Comment by vwochnik** [comment]
I have not worked with Arduino or Seeeduino for a long time. You just have to try and make your adaptions.

**Comment by masalinas** [comment]
I implemented the Arduino Client API to use the MQTT client library from Nikolar O'Relley. I'll make some tests.

Regards.
