### ISSUE TITLE
Question regarding your library:

### ISSUE THREAD

**Issue by ppYodiwo** [vwochnik/sim900client#5]
Hello
I would like to say that your library is really helpful. The fact that you give a client like API makes it easy to use with tha pubsub mqtt library I am using.  I would like to ask you whether you have developed a "secure" version of your client to be used with ssl.

Thank you

**Comment by vwochnik** [comment]
No, I have not and I am not planning on it. On Arduino, you will not be able to handle SSL anyways. It would have to be handled by the GSM modem, probably by issuing some AT commands that tell it to establish an SSL connection.

**Comment by ppYodiwo** [comment]
Thank you for your quick reply.
